name: CI

on:
  push:
    branches:
      - "master"
      - "task/**"
  pull_request:
    branches:
      - "master"
      - "task/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      is_push_image:
        description: "Do you want to push Docker image to Docker Hub ?"
        required: true
        default: true
        type: boolean
      is_deploy_image:
        description: "Do you want to deploy Docker image to AKS ?"
        required: true
        default: true #false
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  maven-compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven Build
        run: |
          cd java-bank  
          mvn compile

  security-check:
    runs-on: ubuntu-latest
    needs: maven-compile

    steps:
      - uses: actions/checkout@v4

      - name: Trivy Installation
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install trivy -y

      - name: Trivy Fs Scan
        run: trivy fs --format table -o fs-report.json .

      - name: Gitleaks Installation
        run: sudo apt-get install gitleaks -y

      - name: Gitleaks Code Scan
        run: gitleaks detect --source . -r gitileaks-report.json --report-format json -f json

      - name: ls -la
        run: ls -la

  maven-test:
    runs-on: ubuntu-latest
    needs: security-check

    steps:
      - uses: actions/checkout@v4

      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Gitleaks Installation
        run: sudo apt-get install maven -y

      - name: Maven unit test
        run: |
          cd java-bank  
          mvn test

  # Build & Push docker image to Docker Hub
  docker_build-push:
    runs-on: ubuntu-latest
    needs: maven-test

    steps:
      - uses: actions/checkout@v4

      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven Build & package
        run: |
          cd java-bank  
          mvn clean package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-bank-jar
          path: java-bank/target/*.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Build Docker Image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: false
      #     tags: kcmchandramoulli/java-bank:latest

      - name: Docker Build
        run: |
          docker build -t kcmchandramoulli/java-bank:latest .

      - name: Trivy Installation
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install trivy -y
  
      - name: Trivy image Scan
        run: trivy image --format table -o image-report.html kcmchandramoulli/java-bank:latest

      # - name: Push Docker Image
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     tags: kcmchandramoulli/java-bank:latest

      - name: Docker Push
        run: |
          docker push kcmchandramoulli/java-bank:latest

  # Push Docker Image to ACR
  #     - name: ACR Login
  #       uses: azure/docker-login@v1
  #       with:
  #         login-server: ${{ secrets.ACR_URL }}
  #         username: ${{ secrets.ACR_USERNAME }}
  #         password: ${{ secrets.ACR_PASSWORD }}

  #     - name: Build and Push Docker Image to ACR
  #       run: |
  #         docker build . -t ${{ secrets.ACR_URL }}/java-bank:latest
  #         docker push ${{ secrets.ACR_URL }}/java-bank:latest

  deploy_to_AKS:
    runs-on: ubuntu-latest
    needs: docker_build-push

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: Azure/login@v2.2.0
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        # creds: # optional
        # ClientId of the Azure Service principal created.
        client-id: ${{ secrets.AZURE_CLIENT_ID }}  # optional
        # TenantId of the Azure Service principal created.
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # optional
        # Azure subscriptionId
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # optional
        auth-type: SERVICE_PRINCIPAL  # optional, default is SERVICE_PRINCIPAL
            
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v3
      with:
        # Resource Group Name
        resource-group: cicd-actions
        # AKS Cluster Name
        cluster-name: cicd-actions-aks
        # # AKS Cluster Subscription
        # subscription: # optional
        # # Get cluster admin credentials. Values: true or false
        # admin: # optional
        # # Enables kubelogin for non-admin user scenario. Values: true or false
        # use-kubelogin: # optional

    - name: Create secret in Kubernetes cluster
      uses: Azure/k8s-create-secret@v4.0
      with:
        # Choose the target Kubernetes namespace. If the namespace is not provided, the commands will run in the default namespace.
        # namespace: # optional
        # Type of Kubernetes secret. Defaults to 'kubernetes.io/dockerconfigjson'.
        secret-type: docker-registry # optional, default is kubernetes.io/dockerconfigjson
        # Name of the secret. You can use this secret name in the Kubernetes YAML configuration file.
        secret-name: docker-image-pull-secret
        # Container Registry URL
        container-registry-url: https://index.docker.io/v1/ # optional
        container-registry-username: ${{ vars.DOCKERHUB_USERNAME }} #${{ secrets.ACR_USERNAME }}  #${{ vars.DOCKERHUB_USERNAME }} # optional
        container-registry-password: ${{ secrets.DOCKERHUB_TOKEN }} #${{ secrets.ACR_PASSWORD }}  #${{ secrets.DOCKERHUB_TOKEN }} # optional

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: latest

    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v4.9
      with:
        manifests: ds.yml
        images: kcmchandramoulli/java-bank:latest
        imagepullsecrets: docker-image-pull-secret
        action: deploy
