  maven-test:
    runs-on: ubuntu-latest
    needs: maven-compile

    steps:
      - uses: actions/checkout@v4

      - name: Checkout another public repository
        uses: actions/checkout@v3
        with:
          repository: kcmchandramouli/java-bank
          path: java-bank

      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Gitleaks Installation
        run: sudo apt-get install maven -y

      - name: Maven unit test
        run: |
          cd java-bank  
          mvn test