  # maven-compile:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Checkout another public repository
  #       uses: actions/checkout@v3
  #       with:
  #         repository: kcmchandramouli/java-bank
  #         path: java-bank

  #     - name: setup JDK 17
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: '17'
  #         distribution: 'temurin'
  #         cache: 'maven'

  #     - name: Maven Build
  #       run: |
  #         cd java-bank  
  #         mvn compile
  # #mvn -B package --file java-bank/pom.xml

name: Maven Compile

on:
  workflow_call: # Makes this workflow reusable
    inputs:
      branch:
        required: false
        type: string
        default: "master"

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven Compile
        run: ls -la  #mvn clean compile